name: nerf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aom=3.3.0=h27087fc_1
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_2
  - cffi=1.15.0=py37h036bc23_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=5.0.1=h594f047_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h7f98852_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_15
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_15
  - libtiff=4.3.0=h542a066_3
  - libuv=1.43.0=h7f98852_0
  - libva=2.14.0=h7f98852_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.13=h22db469_0
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=13.0.1=he0ac6c6_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy-base=1.21.5=py37hf524024_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.2=h166bdaf_1
  - pillow=9.1.0=py37h44f0d7a_2
  - pip=22.0.4=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - setuptools=62.1.0=py37h89c1867_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.2=h4ff8645_0
  - svt-av1=0.9.1=h27087fc_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.11.0=py37_cu113
  - typing_extensions=4.2.0=pyha770c72_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cachetools==5.0.0
    - cycler==0.11.0
    - daal==2021.5.3
    - daal4py==2021.5.3
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - einops==0.3.2
    - entrypoints==0.4
    - fastjsonschema==2.15.3
    - fonttools==4.32.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - future==0.18.2
    - google-auth==2.6.5
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - imageio==2.10.4
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - ipykernel==6.13.0
    - ipython==7.32.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.2.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyter-packaging==0.12.0
    - jupyter-server==1.16.0
    - jupyterlab==3.3.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.12.0
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - kornia==0.6.1
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.2
    - nbclassic==0.3.7
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.5
    - notebook==6.4.10
    - notebook-shim==0.1.0
    - numpy==1.21.6
    - oauthlib==3.2.0
    - open3d==0.13.0
    - opencv-python==4.5.4.58
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plyfile==0.7.2
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.0
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycollada==0.7.1
    - pydeprecate==0.3.1
    - pyglet==1.5.10
    - pygments==2.11.2
    - pymcubes==0.1.2
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.5.2
    - pytorch-ranger==0.1.1
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scikit-learn-intelex==2021.5.3
    - scipy==1.7.3
    - send2trash==1.8.0
    - setuptools-scm==6.4.2
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - tbb==2021.5.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tomli==2.0.1
    - tomlkit==0.10.1
    - torch==1.10.0
    - torch-optimizer==0.3.0
    - torchmetrics==0.8.0
    - torchvision==0.11.1
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.1.1
    - trimesh==3.9.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - werkzeug==2.1.1
    - widgetsnbextension==3.6.0
    - yarl==1.7.2
    - zipp==3.8.0
